on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - '3.7'
          - '3.8'
          - '3.9'
          - '3.10'
          - '3.11'
          - '3.12'
    name: Test in python ${{ matrix.python-version }} 
    steps:
      - uses: actions/checkout@v4
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - run: |-
          pip install -r requirements.txt
          pip install -r test_requirements.txt
      - run: |-
          coverage run --source=py_grpc_prometheus -m pytest 
          coverage report -m
